services:
  web:
    build: .
    user: root
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=true
    depends_on:
      - db
      - css
  
  css:
    build: .
    user: root
    volumes:
      - .:/app
    # Mantenemos el contenedor vivo
    tty: true 
    # Comando explícito que le dice a Tailwind exactamente dónde está todo:
    # -c -> el archivo de configuración
    # -i -> el archivo de entrada
    # -o -> el archivo de salida
    # --watch -> para que se quede vigilando
    command: >
      bundle exec tailwindcss
      -c ./tailwind.config.js
      -i ./app/assets/stylesheets/application.tailwind.css
      -o ./app/assets/builds/application.css
      --watch
    depends_on:
      - db
    
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password

volumes:
  postgres_data:
