databases:
  - name: mel-database
    plan: free # El plan gratuito de Render para Postgres

services:
  - type: web
    name: mel-app
    plan: free
    env: docker # Le decimos a Render que use nuestro Dockerfile
    # No se necesita 'startCommand' porque Render usará el 'CMD' de tu Dockerfile.
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mel-database
          property: connectionString
      - key: RAILS_MASTER_KEY
        generateValue: true