databases:
  - name: mel-database
    plan: free

services:
  - type: web
    name: mel-app
    plan: free
    env: docker # Le decimos a Render que use nuestro Dockerfile
    healthCheckPath: /up # La ruta que Render usará para saber si la app está viva
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mel-database
          property: connectionString
      - key: RAILS_MASTER_KEY
        generateValue: true
      - key: SECRET_KEY_BASE
        generateValue: true