services:
  - type: pserv
    name: mel-database

  - type: web
    name: mel-app
    env: docker # Le decimos a Render que use nuestro Dockerfile
    plan: free
    # Variables de entorno necesarias para Rails y la conexión a la BD
    envVars:
      - key: RAILS_MASTER_KEY
        generateValue: true # Render genera una clave segura por nosotros
   
      - key: DATABASE_URL
        fromDatabase:
          name: mel-database 
          property: connectionString