databases:
  - name: mel-database
    plan: free

services:
  - type: web
    name: mel-app
    plan: free
    env: docker
    # --- ¡AQUÍ ESTÁ LA SOLUCIÓN! ---
    # Le decimos a Render explícitamente qué puerto debe revisar.
    healthCheckPath: /up # Usa la ruta de chequeo de Rails
    # ---------------------------------
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mel-database
          property: connectionString
      - key: RAILS_MASTER_KEY
        generateValue: true